let items = [
    {
        name: "Veg cheese Burger",
        price: 60,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Paneer grill Sandwich",
        price: 70,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Veg noodles",
        price: 40,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "veg fried rice",
        price: 50,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Paneer pakora",
        price: 100,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken cheese Burger",
        price: 90,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/chicken_cheese_Burger.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739354021",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken noodles",
        price: 70,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken fried rice",
        price: 80,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken cheese pakora",
        price: 150,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken cutlets",
        price: 70,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf230b7eda1ca7768460e",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer roll",
        price: 100,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Delhi special Hakka noodles",
        price: 199,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer fried rice",
        price: 130,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "veg sandwich",
        price: 80,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer burger",
        price: 130,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken dry fry",
        price: 120,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken pakora",
        price: 120,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken fried momo",
        price: 90,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken roll",
        price: 100,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken sandwich",
        price: 120,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63edf2a5b7eda1ca77684610",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Butter cheese pav bhaji",
        price: 90,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "veg cheese momos",
        price: 60,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Gajar halwa",
        price: 50,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "fruit custard",
        price: 40,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer paratha",
        price: 80,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chole bhature",
        price: 60,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "butter cheese Vada pav",
        price: 60,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Dhokla",
        price: 20,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "butter chole kulche",
        price: 80,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "butter cheese dabeli",
        price: 70,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee02c7b7eda1ca77684614",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Oreo shake",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "cold coffee",
        price: 25,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "mix fruit plate",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "fruits",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "mango shake",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "watermelon plate",
        price: 25,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "fruits",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "papaya plate",
        price: 25,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "fruits",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Banana shake",
        price: 20,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Haldi milk",
        price: 20,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Badam Shake",
        price: 25,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "lassi",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0332b7eda1ca77684616",
        category: "juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "Maysore Dosa",
        price: 40,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "fried meggi",
        price: 20,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "Aloo Paratha",
        price: 20,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "pizza dosa",
        price: 100,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "Aloo cheese sandwich",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "chicken burger",
        price: 40,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "chicken fried rice",
        price: 45,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "chicken curry",
        price: 50,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "chicken roll",
        price: 40,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee037fb7eda1ca7768461a",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 200,
    },
    {
        name: "veg biryani",
        price: 120,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "Hyd Dum biryani",
        price: 165,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "paneer utthapam",
        price: 50,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "pizza dosa",
        price: 90,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "sambar vada",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "plain pesarattu",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "paneer dosa",
        price: 50,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "egg biryani",
        price: 150,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "Mysore bajji",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "sambar idli",
        price: 25,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee03c1b7eda1ca7768461c",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1100,
        endTime: 2300,
    },
    {
        name: "classic Burger",
        price: 90,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "paneer maharaja burger",
        price: 135,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "butter chilli meggi",
        price: 50,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "vanilla fidge",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "hot chocolate",
        price: 30,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "chicken popcorn",
        price: 120,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "chicken meggi magic",
        price: 90,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "chicken strips",
        price: 229,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "chicken patty",
        price: 20,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "monster burger",
        price: 159,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0408b7eda1ca77684620",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 730,
        endTime: 2200,
    },
    {
        name: "veg chilli momo",
        price: 95,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer pav bhaji",
        price: 85,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "veg cutlets",
        price: 40,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/chicken_cutlets.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739745414",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: "10 am",
        endTime: "10pm",
    },
    {
        name: "fried rice (paneer)",
        price: 95,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "paneer nuggets",
        price: 127,
        type: "veg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken cutlets",
        price: 60,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken strips",
        price: 107,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "fish fried rice",
        price: 125,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "chicken chowmin",
        price: 75,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "nonveg",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
    {
        name: "classic chicken",
        price: 97,
        type: "nonveg",
        photo: "https://ik.imagekit.io/c7u7l7qa8/01OXYV37YDZS524W4WJREYX6V2ZL5EMOJZ_9blPMAm7d95.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1675235641775",
        shopkeeperId: "63ee0433b7eda1ca77684624",
        category: "fastfood",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        startTime: 1000,
        endTime: 2200,
    },
];
require("dotenv").config();
const Item = require("./models/item.model");
const mongoose = require("mongoose");
mongoose.set("strictQuery", false);
mongoose
    .connect(
        "mongodb+srv://admin:admin@kamengkriticlean.kenyqqe.mongodb.net/?retryWrites=true&w=majority"
    )
    .then(() => {
        console.log("DB Connected");
        items.map(async (item) => {
            // console.log(item);
            const newItem = await Item.create({ ...item });
            console.log(newItem);
        });
        console.log("done");
        // process.exit(0);
    })
    .catch((e) => {
        console.log(e);
        process.exit(1);
    });
