// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKWQ9IPJS1J9Aenqf7jgr0EkAZ1dUxC0',
    appId: '1:357443788060:android:ed6b640a6da34db9cf6ed9',
    messagingSenderId: '357443788060',
    projectId: 'kriti-12c33',
    storageBucket: 'kriti-12c33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjcG3-xzcYMcIojfIJHbRILmG82TOMkhA',
    appId: '1:357443788060:ios:0e0d19bbb67e9643cf6ed9',
    messagingSenderId: '357443788060',
    projectId: 'kriti-12c33',
    storageBucket: 'kriti-12c33.appspot.com',
    androidClientId: '357443788060-nd98urvlhica4duv0go5gt0rjgvuhnt4.apps.googleusercontent.com',
    iosClientId: '357443788060-ge2k65m8ts6bsg142ds51cf4tr1iri86.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogue',
  );
}
